#!/bin/bash
set -e
HERE=$(dirname $0)
ROOT=$HERE/..

EXE=dbmigrations-tests
TEST=$HERE/../test
BUILDDIR=$TEST/dist
cabal configure -f testing --builddir=$BUILDDIR
cabal build --builddir=$BUILDDIR --ghc-options="-Wall -Werror"

cd test

./dist/build/$EXE/$EXE
